services:
  dashboard:
    image: ghcr.io/ninanor/dashboard-dashboard:main
    env_file: "stack.env"
  rclone:
    image: rclone/rclone:1.69
    command: serve http nirds3:bencretois-ns8129k-proj-tabmon --addr :8081 --baseurl /data/
    volumes:
      - /home/benjamin.cretois/.config/rclone/:/root/.config/rclone/
    environment:
      - RCLONE_CONFIG=/root/.config/rclone/rclone.conf #for portainer /run/secrets/rclone.conf
  reverseproxy:
    image: ghcr.io/ninanor/dashboard-proxy:main
    ports:
      - 8085:80
