services:
  dashboard:
    build:
      context: .
    volumes:
      - ./assets/:/app/assets:ro
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
  rclone:
    image: rclone/rclone:1.69
    command: serve http . --addr :8081
  reverseproxy:
    build: proxy
    ports:
      - 8081:80
