version: '3.8'

services:
  dashboard:
    build:
      context: .
    env_file:
      - .env
    secrets:
      - htpasswd
  #image: ghcr.io/ninanor/dashboard-dashboard:main
  reverseproxy:
    build: proxy
    image: ghcr.io/ninanor/dashboard-proxy:main
    secrets:
      - htpasswd
    ports:
      - 8085:80
  rclone:
    image: rclone/rclone:1.69
    command: serve http nirds3:bencretois-ns8129k-proj-tabmon --addr :8081 --baseurl /data/
    environment:
      RCLONE_CONFIG: /run/secrets/tabmon_rclone
    secrets:
      - tabmon_rclone

secrets:
  tabmon_rclone:
    file: ~/.config/rclone/rclone.conf
  htpasswd:
    file: ~/htpasswd.txt
