version: '3.8'

services:
  dashboard:
    build:
      context: .
    #image: ghcr.io/ninanor/dashboard-dashboard:main
    #env_file: "stack.env"
  reverseproxy:
    image: ghcr.io/ninanor/dashboard-proxy:main
    ports:
      - 8085:80
  rclone:
    image: rclone/rclone:1.69
    command: serve http nirds3:bencretois-ns8129k-proj-tabmon --addr :8081 --baseurl /data/
    environment:
      RCLONE_CONFIG: /run/secrets/tabmon_rclone
    secrets:
      - tabmon_rclone

secrets:
  tabmon_rclone:
    file: /home/benjamin.cretois/.config/rclone/rclone.conf # external: true for portainer
