[global]
email = ""

[server]
enableCORS = false
enableXsrfProtection = false

[theme]
backgroundColor = "#FFFFFF"  # background of the whole app
font = "sans serif"
primaryColor = "#2E86AB"
secondaryBackgroundColor = "#F0F2F6"  # side dashboard
textColor = "#262730"
